---
# ansible-playbook -i inventario playbook-3.yml
- name: "Esempio 3: qualcosa di più complesso"
  hosts: web
  become: true

  tasks:

  - name: Ensure nginx is installed
    # https://docs.ansible.com/ansible/latest/modules/package_module.html
    # https://docs.ansible.com/ansible/latest/modules/apt_module.html
    apt:
      name: nginx
      cache_valid_time: 7200

  - name: Remove default site
    file:
      name: /etc/nginx/sites-enabled/default
      state: absent
    notify: reload nginx

  - name: Configure example website
    copy:
      src: "example-site.conf.j2"
      dest: /etc/nginx/sites-available/example-site.conf
      owner: root
      group: root
      mode: "644"
    notify: reload nginx

  - name: Enable example website
    file:
      src: /etc/nginx/sites-available/example-site.conf
      dest: /etc/nginx/sites-enabled/example-site.conf
      state: link
    notify: reload nginx


  handlers:
  - name: reload nginx
    service:
      name: nginx
      state: reloaded
